name: Build and Deploy Bot

on:
  push:
    branches:
      - main  # Запуск при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest  # Операционная система для выполнения

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Java 21
        uses: actions/setup-java@v3  # Устанавливаем Java
        with:
          distribution: 'temurin'  # Указываем поставщика Java
          java-version: '21'  # Устанавливаем Java 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # Даём права на выполнение gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar  # Запускаем shadowJar для сборки fat JAR

      - name: Get latest tag
        id: get_tag
        run: echo "TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar  # Указываем путь к JAR-файлу
          tag_name: ${{ env.TAG }}  # Используем уникальный тег (дата/время)
          release_name: "Release ${{ env.TAG }}"  # Название релиза
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Токен GitHub

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Подключение к серверу и запуск update_bot.sh
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            chmod +x ~/bot/update_bot.sh
            ~/bot/update_bot.sh
